name: Node.js Enterprise Deployment via SSM (OIDC Edition)

on: 
    push:
        branches:
            - feature/test-pipeline

permissions:
    id-token: write
    contents: read

env:
    AWS_REGION: "ap-southeast-1"
    S3_BUCKET_NAME: "my-enterprise-deploy-bucket-2026"
    EC2_INSTANCE_ID: "i-0e4c460063e83395b"
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '24'

            - name: Install dependencies
              run: npm ci --omit=dev

            - name: Zip Artifacts
              run: zip -r deploy.zip . -x "*.git*" "*.github*" "node_modules/*"

            # ĐĂNG NHẬP KHÔNG DÙNG KEY: Dùng OIDC để mượn Role trực tiếp từ AWS
            - name: Configure AWS Credentials via OIDC
              uses: aws-actions/configure-aws-credentials@v4
              with:
                    role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                    aws-region: ${{ env.AWS_REGION }}
                    audience: sts.amazonaws.com

            - name: Upload Deploy Zip to S3
              run: |
                aws s3 cp deploy.zip s3://${{ env.S3_BUCKET_NAME }}/deploy.zip

            - name: Trigger AWS SSM Run Command to Deploy
              run: |
                aws ssm send-command \
                --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
                --document-name "AWS-RunShellScript" \
                --comment "Deploying NodeJS App via GitHub Actions" \
                --parameters 'commands=[
                    "cd /var/www/nodejs-cicd",
                    "aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/deploy.zip .",
                    "unzip -o deploy.zip",
                    "rm deploy.zip",
                    "pm2 describe enterprise-app > /dev/null && pm2 reload enterprise-app --update-env || NODE_ENV=production PORT=3000 pm2 start server.js --name \"enterprise-app\""
                ]' \
                --region ${{ env.AWS_REGION }}


            





                